name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14-dev']
        install: ['pymsbuild>=1.0', 'pymsbuild>=1.0a1']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install ${{ matrix.install }} -r tests/requirements.txt
    - name: Test with pytest
      run: pytest
    - name: Check self build (sdist)
      run: python -m pymsbuild sdist
    - name: Check self build (wheel)
      run: python -m pymsbuild wheel
